name = "mfm-corporation"
main = "src/index.js"
compatibility_date = "2024-05-16"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "mfm-corporation-db"
database_id = "91e8699c-2731-4f0d-8a09-9f9765e7e4cc"

# KV namespace binding
[[kv_namespaces]]
binding = "KV_BINDING"
id = "b7fb55a0476d41b395fb36cf64b0a317"
preview_id = "b7fb55a0476d41b395fb36cf64b0a317"

# R2 bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mfm-corporation-uploads"
