// PDF Tool — generate PDFs via PDFShift API, store in R2, return public URL
// Primary: PDFShift API (PDFSHIFT_API_KEY). Fallback: store HTML in R2.
// Requires: PDFSHIFT_API_KEY (optional), env.R2 bucket binding

import { logger } from '../core/logger.js';

const PDFSHIFT_URL = 'https://api.pdfshift.io/v3/convert/pdf';

// ─── Generate PDF from HTML string ────────────────────────────────────────

export async function generatePDF(title, htmlContent, env) {
  const fileName = `reports/${title.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`;

  // Try PDFShift if API key present
  if (env.PDFSHIFT_API_KEY) {
    try {
      const res = await fetch(PDFSHIFT_URL, {
        method: 'POST',
        headers: {
          Authorization: `Basic ${btoa(`api:${env.PDFSHIFT_API_KEY}`)}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          source: htmlContent,
          landscape: false,
          use_print: true,
          format: 'A4',
          margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' }
        })
      });
      if (res.ok) {
        const pdfBuffer = await res.arrayBuffer();
        if (env['mfm-corporation-uploads']) {
          await env['mfm-corporation-uploads'].put(fileName, pdfBuffer, {
            httpMetadata: { contentType: 'application/pdf' }
          });
          logger.info('pdf-tool', 'pdf_generated_pdfshift', { fileName });
          return { url: `https://mfm-corporation-uploads.r2.dev/${fileName}`, fileName };
        }
      }
    } catch (err) {
      logger.warn('pdf-tool', 'pdfshift_failed', { error: err.message });
    }
  }

  // Fallback: store HTML in R2 as downloadable report
  if (env['mfm-corporation-uploads']) {
    try {
      const htmlFileName = fileName.replace('.pdf', '.html');
      const fullHtml = wrapHtml(title, htmlContent);
      await env['mfm-corporation-uploads'].put(htmlFileName, fullHtml, {
        httpMetadata: { contentType: 'text/html' }
      });
      logger.info('pdf-tool', 'html_fallback_stored', { htmlFileName });
      return { url: `https://mfm-corporation-uploads.r2.dev/${htmlFileName}`, fileName: htmlFileName };
    } catch (err) {
      logger.error('pdf-tool', 'r2_upload_failed', { error: err.message });
    }
  }

  logger.warn('pdf-tool', 'no_storage_available', {});
  return null;
}

// ─── Generate PDF from plain markdown/text content ─────────────────────

export async function generateReportPDF(title, markdownContent, env) {
  const html = markdownToHtml(markdownContent);
  return await generatePDF(title, html, env);
}

// ─── Helpers ──────────────────────────────────────────────────────────────

function wrapHtml(title, body) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
<style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#333;}
h1{color:#1a1a2e;border-bottom:2px solid #e94560;padding-bottom:8px;}
h2{color:#16213e;}table{width:100%;border-collapse:collapse;}
th,td{border:1px solid #ddd;padding:8px;text-align:left;}
th{background:#f5f5f5;}pre{background:#f5f5f5;padding:10px;border-radius:4px;overflow-x:auto;}
</style></head><body><h1>${title}</h1>${body}
<hr><p style="color:#999;font-size:12px">Generated by MFM Corporation AI — ${new Date().toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'})}</p>
</body></html>`;
}

function markdownToHtml(md) {
  return md
    .replace(/^#{3}\s(.+)/gm, '<h3>$1</h3>')
    .replace(/^#{2}\s(.+)/gm, '<h2>$1</h2>')
    .replace(/^#{1}\s(.+)/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>')
    .replace(/^- (.+)/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[hup])/gm, '<p>')
    .replace(/(?<![>])\n(?![<])/g, '<br>');
}
